services:
  app:
    build: .
    ports:
      - "7701:7701"
    network_mode: host
    depends_on:
      - redis

  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
    command: redis-server --save 60 1 --protected-mode no --appendonly yes --dir data/redis
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local