services:
  app:
    build: .
    ports:
      - "7701:7701"
    network_mode: host
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --protected-mode no --appendonly yes
    volumes:
      - redis:/data

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    environment:
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis

volumes:
  redis:
    driver: local