services:
  web:
    build: .
    ports:
      - "7701:7701"
    depends_on:
      - redis

  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--save 60 1 --appendonly yes --protected-mode no
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local