server.port: 7701

github:
  url: https://api.github.com/users/
#  token: personal-access-token

calculations:
  scale: 10
  rounding-mode: HALF_UP

redis:
  host: localhost
  port: 6379

logging:
  level:
    com.github.magdevlena: TRACE